version: "2"
services:
  jks:
    image: jenkins/jenkins:latest
    ports:
      - 50001:8080
      - 50000:50000
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /bin/docker:/bin/docker
    container_name: jks
    user: root